### PR TITLE
 Changes to update IKS URL and error model

### PR DESCRIPTION
**Pull request by prgavali**
Tested Volume attach and detach for IKS endpoint 

{"level":"info","ts":"2019-07-04T13:08:12.467+0530","caller":"provider/get_volume_attachment.go:61","msg":"Successfuly retrived volume attachment","RequestID":"c08ec9bf-4913-4540-8cc1-37ad868fd20b","volumeAttachmentResponse":{"volumeID":"94fe85e8-82fa-433a-a33a-9e76094ef181","instanceID":"","vpcVolumeAttachment":{"id":"e2add264-d701-4495-a350-e2d544ea9e9f","name":"wrecker-obsolete-sleeve-twig-ecologist","type":"data"},"iksVolumeAttachment":null,"status":"attached"}}
{"level":"info","ts":"2019-07-04T13:08:12.467+0530","caller":"provider/get_volume_attachment.go:40","msg":"Volume attachment response","RequestID":"c08ec9bf-4913-4540-8cc1-37ad868fd20b","volumeAttachmentResponse":{"volumeID":"94fe85e8-82fa-433a-a33a-9e76094ef181","instanceID":"","vpcVolumeAttachment":{"id":"e2add264-d701-4495-a350-e2d544ea9e9f","name":"wrecker-obsolete-sleeve-twig-ecologist","type":"data"},"iksVolumeAttachment":null,"status":"attached"}}
{"level":"info","ts":"2019-07-04T13:08:12.467+0530","caller":"provider/wait_for_attach_volume.go:37","msg":"Volume attachment is complete","RequestID":"c08ec9bf-4913-4540-8cc1-37ad868fd20b","retry attempt":1,"max retry attepmts":4,"currentVolAttachment":{"volumeID":"94fe85e8-82fa-433a-a33a-9e76094ef181","instanceID":"","vpcVolumeAttachment":{"id":"e2add264-d701-4495-a350-e2d544ea9e9f","name":"wrecker-obsolete-sleeve-twig-ecologist","type":"data"},"iksVolumeAttachment":null,"status":"attached"}}

### CODE REVIEW

**Comment by arahamad** [comment]
@pramodgavali , Can you test the error handling part as well. I mean to say negative tests at least attaching same volume again or deleting volume twice

**Comment by prgavali** [comment]
{"level":"info","ts":"2019-07-04T09:40:24.579Z","caller":"provider/detach_volume.go:55","msg":"No volume attachment found for","RequestID":"1406ab30-59b9-400c-8bcf-b5eb3594af54","currentVolAttachment":null,"error":"{Code:VolumeAttachFindFailed, Type:RetrivalFailed, Description:Failed to find the volume attachment by using volume ID :'57bf8765-8027-4adf-8ba7-d70966efdbe0' and instance ID : 'test-bk0ems5206ni7asstvh0-mycluster1v-default-000003f6'., BackendError:No VolumeAttachment Found, RC:400}"}

**Comment by prgavali** [comment]
{"level":"info","ts":"2019-07-05T13:01:47.305Z","caller":"provider/detach_volume.go:52","msg":"Successfully detached volume from VPC provider","RequestID":"342cac86-a401-4296-9691-b34c02f59078","respError":"json: unsupported type: func() (io.ReadCloser, error)"}

**Comment by arahamad** [comment]
> {"level":"info","ts":"2019-07-05T13:01:47.305Z","caller":"provider/detach_volume.go:52","msg":"Successfully detached volume from VPC provider","RequestID":"342cac86-a401-4296-9691-b34c02f59078","respError":"json: unsupported type: func() (io.ReadCloser, error)"}

Is this issue or expected ?

**Pull request merged**
